### ISSUE TITLE
Infinite loop in handleOutputLayoutChange

### ISSUE THREAD

**Issue by ifreund** [ifreund/river#175]
This can be reproduced by  closing the window used by a nested river session. Not sure if this is a river issue or wlroots issue, the infinite loop happens within wlroots code but river could have caused the list to enter this invalid state.
```
(gdb) bt
#0  wlr_output_layout_get (layout=0x1029d80, reference=0xfcb430) at ../types/wlr_output_layout.c:227
#1  0x00007f6f99b145ea in wlr_output_layout_get_box (layout=0x1029d80, reference=0xfcb430) at ../types/wlr_output_layout.c:370
#2  0x000000000024d40d in OutputManager.createHead (self=0x7ffc890f2380, output=0x1029d80, config=0xfb5eb0) at OutputManager.zig:289
#3  0x0000000000238265 in OutputManager.ouputConfigFromCurrent (self=0x7ffc890f2380) at OutputManager.zig:278
#4  0x000000000023895a in OutputManager.handleOutputLayoutChange (listener=0x7ffc890f23d8, output_layout=0xfc70d0) at OutputManager.zig:108
#5  .wayland.wayland_server_core.struct:451:17.wrapper (listener=0x7ffc890f23d8, data=0xfc70d0) at /home/ifreund/projects/river/zig-cache/zig-wayland/wayland_server_core.zig:453
#6  0x00007f6f99b2b933 in wlr_signal_emit_safe (signal=0xfc70f8, data=0xfc70d0) at ../util/signal.c:29
#7  0x00007f6f99b13c36 in output_layout_reconfigure (layout=0xfc70d0) at ../types/wlr_output_layout.c:130
#8  0x00007f6f99b13d69 in handle_output_destroy (listener=0xffa680, data=0xfcb430) at ../types/wlr_output_layout.c:166
#9  0x00007f6f99b2b933 in wlr_signal_emit_safe (signal=0xfcb678, data=0xfcb430) at ../util/signal.c:29
#10 0x00007f6f99b188f6 in wlr_output_destroy (output=0xfcb430) at ../types/wlr_output.c:373
#11 0x00007f6f99ae4d49 in xdg_toplevel_handle_close (data=0xfcb430, xdg_toplevel=0xfcb880) at ../backend/wayland/output.c:483
#12 0x00007f6f9973fe6d in  () at /usr/lib/libffi.so.7
#13 0x00007f6f9973f2aa in  () at /usr/lib/libffi.so.7
#14 0x00007f6f9972ca1f in wl_closure_invoke (closure=closure@entry=0x10bf6a0, target=<optimized out>, target@entry=0xfcb880, opcode=opcode@entry=1, data=<optimized out>, flags=1)
    at ../src/connection.c:1018
#15 0x00007f6f9972ded3 in dispatch_event (display=display@entry=0x90b090, queue=<optimized out>) at ../src/wayland-client.c:1445
#16 0x00007f6f9972e26c in dispatch_queue (queue=0x90b160, display=0x90b090) at ../src/wayland-client.c:1591
#17 wl_display_dispatch_queue_pending (display=0x90b090, queue=0x90b160) at ../src/wayland-client.c:1833
#18 0x00007f6f99ae2711 in dispatch_events (fd=6, mask=1, data=0x90ae90) at ../backend/wayland/backend.c:46
#19 0x00007f6f99c6b672 in wl_event_loop_dispatch (loop=0x904cf0, timeout=timeout@entry=-1) at ../src/event-loop.c:1027
#20 0x00007f6f99c6cad5 in wl_display_run (display=0x90ad20) at ../src/wayland-server.c:1351
#21 0x000000000021d8d9 in main () at main.zig:137
#22 0x00000000002206c2 in std.start.callMain () at /home/ifreund/.local/lib/zig/std/start.zig:344
#23 std.start.initEventLoopAndCallMain () at /home/ifreund/.local/lib/zig/std/start.zig:286
#24 std.start.callMainWithArgs (argc=1, argv=0x7ffc890f29d8, envp=...) at /home/ifreund/.local/lib/zig/std/start.zig:249
#25 std.start.main (c_argc=1, c_argv=0x7ffc890f29d8, c_envp=0x7ffc890f29e8) at /home/ifreund/.local/lib/zig/std/start.zig:256
(gdb) s
226             wl_list_for_each(l_output, &layout->outputs, link) {
(gdb) s
227                     if (l_output->output == reference) {
(gdb) p layout->outpus
There is no member named outpus.
(gdb) p layout->outputs
$1 = {prev = 0xfc7410, next = 0xfcb430}
(gdb) p layout->outputs->next
$2 = (struct wl_list *) 0xfcb430
(gdb) p *layout->outputs->next
$3 = {prev = 0x7f6f99b6c860 <output_impl>, next = 0x90ae90}
(gdb) p *layout->outputs->next->next
$4 = {prev = 0x7f6f99b707e0 <backend_impl>, next = 0xfbd670}
(gdb) p *layout->outputs->next->next->next
$5 = {prev = 0x90ae98, next = 0x90ae98}
(gdb) p *layout->outputs->next->next->next->next
$6 = {prev = 0xfbd670, next = 0xfbd670}
(gdb) p *layout->outputs->next->next->next->next->next
$7 = {prev = 0x90ae98, next = 0x90ae98}
(gdb) p *layout->outputs->next->next->next->next->next->next
$8 = {prev = 0xfbd670, next = 0xfbd670}
(gdb) p *layout->outputs->next->next->next->next->next->next->next
$9 = {prev = 0x90ae98, next = 0x90ae98}
(gdb) p *layout->outputs->next->next->next->next->next->next->next->next
$10 = {prev = 0xfbd670, next = 0xfbd670}
(gdb) 
```

**Comment by ifreund** [comment]
This is fixed by https://github.com/swaywm/wlroots/commit/44b1ff16e9bc9d3a0afc86c1afafd1efcdada806

**Comment by ifreund** [comment]
9e3e92050e04320949c6cd995273c30319ebd515
